// Generated by CoffeeScript 1.7.1
(function() {
  var COINBASE_URL, buy_with_bitbuy;

  console.log("loaded");

  COINBASE_URL = "https://coinbase.com/oauth/authorize?response_type=code&client_id=2af562103350eca06528b58789d77955ec9c7d3b8d794b16827bea600e7817c3&redirect_uri=http://localhost:2000/coinbase";

  buy_with_bitbuy = function(opts, cb) {
    return $.post('http://localhost:2000/buy', opts, function(data) {
      var codes, tokens;
      data = JSON.parse(data);
      tokens = data.tokens;
      store("tokens", tokens);
      codes = data.codes;
      return cb(codes);
    });
  };

  $(function() {
    window.onmessage = function(e) {
      console.log(e.data);
      store('tokens', e.data);
      return buy_with_bitbuy();
    };
    add_bitbuy_button();
    buy_with_bitbuy = function() {
      var amount, tokens;
      amount = parseFloat(get_amount(), 10) * 100;
      tokens = store("tokens");
      return buy_with_bitbuy({
        tokens: tokens,
        amount: amount,
        site: "amazon"
      }, function(cards) {
        apply_cards(cards, 0);
        return place_order();
      });
    };
    return $('#buy-with-bitbuy').on('click', function(e) {
      e.preventDefault();
      if (store("tokens")) {
        return buy_with_bitbuy();
      } else {
        return window.open(COINBASE_URL, '', 'width=900,height=600');
      }
    });
  });

}).call(this);
