// Generated by CoffeeScript 1.7.1
(function() {
  var COINBASE_URL, buy_with_bitbuy, injectCSS, loc;

  console.log("loaded");

  COINBASE_URL = "https://coinbase.com/oauth/authorize?response_type=code&client_id=2af562103350eca06528b58789d77955ec9c7d3b8d794b16827bea600e7817c3&redirect_uri=http://localhost:2000/coinbase";

  buy_with_bitbuy = function(opts, cb) {
    return $.post('http://localhost:2000/buy', opts, function(data) {
      var codes, tokens;
      tokens = data.tokens;
      store("tokens", tokens);
      codes = data.codes;
      return cb(codes);
    });
  };

  loc = document.location.href;

  document.addEventListener('DOMSubtreeModified', injectCSS, false);

  injectCSS = function() {
    var style;
    if (document.head) {
      document.removeEventListener('DOMSubtreeModified', injectCSS, false);
      style = document.createElement('style');
      style.innerHTML = '#spc-top > div > div.a-span-last > div > div.a-span-last { visibility: hidden !important; }';
      return document.head.appendChild(style);
    }
  };

  $(function() {
    var buy;
    window.onmessage = function(e) {
      var data;
      data = JSON.parse(e.data);
      console.log(data);
      if (data.access_token && data.refresh_token && data.code) {
        store('tokens', data);
        return buy();
      } else {
        return console.log("this ain't me.");
      }
    };
    add_bitbuy_button();
    buy = function() {
      var amount, tokens;
      amount = parseFloat(get_amount(), 10) * 100;
      tokens = store("tokens");
      return buy_with_bitbuy({
        tokens: tokens,
        amount: amount,
        site: "amazon"
      }, function(cards) {
        apply_cards(cards, 0);
        return place_order();
      });
    };
    return $('#buy-with-bitbuy').on('click', function(e) {
      e.preventDefault();
      if (store("tokens")) {
        return buy();
      } else {
        return window.open(COINBASE_URL, '', 'width=900,height=600');
      }
    });
  });

}).call(this);
